enozomApp.constant('StudentStatus', {
    APPLICATIONFEES: 1,
    APPLICATIONWITHPARENT: 2,
    APPLICATIONNOTENTERED: 3,
    WAITINGINTERVIEW: 4,
    FORMCOMPLETED: 5,
    STUDENT: 6,
    REJECTED: 7,
    WITHDRAW: 8
});